title = "Roxy example for testing while developing"

[website]

[project]
input = ".org"
output = ".html"

[providers]
custom = "../custom.so"

[plugin.custom]
flag = true
[plugin.custom.submap]
thing = 1
thing2 = 6
